plugins {
	id 'java-library'
	id 'maven-publish'
	id 'net.neoforged.moddev' version '2.0.148'
}

version = mod_version
group = 'com.shownametag'
base { archivesName = 'shownametag-neoforge' }

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
	version = project.neo_version
	runs {
		client {
			client()
		}
	}
	mods {
		"${mod_id}" {
			sourceSet sourceSets.main
		}
	}
}

tasks.withType(ProcessResources).configureEach {
	var replaceProperties = [
		minecraft_version: minecraft_version, neo_version: neo_version,
		mod_id: mod_id, mod_name: mod_name, mod_version: mod_version,
		mod_license: mod_license, mod_authors: mod_authors, mod_description: mod_description
	]
	inputs.properties replaceProperties
	filesMatching(['META-INF/neoforge.mods.toml']) {
		expand replaceProperties
	}
}

// Ortak kaynak kodu (Mixin + mixin ayari) tek yerde: ../../common
sourceSets.main {
	java.srcDir '../../common/java'
	resources.srcDir '../../common/resources'
}
